<?php

declare(strict_types=1);

namespace LPhenom\LPhenom\Tests;

use LPhenom\LPhenom\Build\KphpEntrypointGenerator;
use PHPUnit\Framework\TestCase;

/**
 * Tests for KphpEntrypointGenerator.
 *
 * Verifies that the generated entrypoint:
 *   - Is a temporary build artifact (not committed)
 *   - Contains only kphp-compatible files
 *   - Excludes files annotated with shared-only or none
 *   - Has correct dependency order
 *   - Includes the smoke test block
 */
final class KphpEntrypointGeneratorTest extends TestCase
{
    private string $basePath;

    protected function setUp(): void
    {
        $this->basePath = dirname(__DIR__);
    }

    public function testGenerateCreatesFile(): void
    {
        $outputPath = sys_get_temp_dir() . '/lphenom_kphp_test_' . uniqid() . '.php';

        try {
            $generator = KphpEntrypointGenerator::createDefault($this->basePath);
            $count = $generator->generate($outputPath);

            self::assertFileExists($outputPath);
            self::assertGreaterThan(0, $count);
        } finally {
            if (is_file($outputPath)) {
                unlink($outputPath);
            }
        }
    }

    public function testGeneratedFileIsSyntacticallyValid(): void
    {
        $outputPath = sys_get_temp_dir() . '/lphenom_kphp_syntax_' . uniqid() . '.php';

        try {
            $generator = KphpEntrypointGenerator::createDefault($this->basePath);
            $generator->generate($outputPath);

            // php -l checks syntax without executing
            $result = 0;
            $output = [];
            exec('php -l ' . escapeshellarg($outputPath) . ' 2>&1', $output, $result);

            self::assertSame(0, $result, 'Generated file has syntax errors: ' . implode("\n", $output));
        } finally {
            if (is_file($outputPath)) {
                unlink($outputPath);
            }
        }
    }

    public function testGeneratedFileContainsSmokeTest(): void
    {
        $outputPath = sys_get_temp_dir() . '/lphenom_kphp_smoke_' . uniqid() . '.php';

        try {
            $generator = KphpEntrypointGenerator::createDefault($this->basePath);
            $generator->generate($outputPath);

            $content = file_get_contents($outputPath);
            self::assertIsString($content);
            self::assertStringContainsString('Smoke test', $content);
            self::assertStringContainsString('LPhenom\\Core\\Config\\Config', $content);
            self::assertStringContainsString('LPhenom\\LPhenom\\Application', $content);
        } finally {
            if (is_file($outputPath)) {
                unlink($outputPath);
            }
        }
    }

    public function testGeneratedFileContainsAutoGeneratedWarning(): void
    {
        $outputPath = sys_get_temp_dir() . '/lphenom_kphp_warn_' . uniqid() . '.php';

        try {
            $generator = KphpEntrypointGenerator::createDefault($this->basePath);
            $generator->generate($outputPath);

            $content = file_get_contents($outputPath);
            self::assertIsString($content);
            self::assertStringContainsString('AUTO-GENERATED', $content);
            self::assertStringContainsString('do not edit manually', $content);
        } finally {
            if (is_file($outputPath)) {
                unlink($outputPath);
            }
        }
    }

    public function testExcludesSharedOnlyFiles(): void
    {
        $outputPath = sys_get_temp_dir() . '/lphenom_kphp_exclude_' . uniqid() . '.php';

        try {
            $generator = KphpEntrypointGenerator::createDefault($this->basePath);
            $generator->generate($outputPath);

            $content = file_get_contents($outputPath);
            self::assertIsString($content);

            // shared-only files must NOT appear
            self::assertStringNotContainsString('PdoMySqlConnection.php', $content);
            self::assertStringNotContainsString('PdoResult.php', $content);
            self::assertStringNotContainsString('ConnectionFactory.php', $content);
            self::assertStringNotContainsString('PhpRedisClient.php', $content);
            self::assertStringNotContainsString('PhpRedisPipelineDriver.php', $content);
            self::assertStringNotContainsString('RedisConnector.php', $content);
            self::assertStringNotContainsString('RedisSubscriber.php', $content);
            self::assertStringNotContainsString('PollHandler.php', $content);
        } finally {
            if (is_file($outputPath)) {
                unlink($outputPath);
            }
        }
    }

    public function testExcludesNoneFiles(): void
    {
        $outputPath = sys_get_temp_dir() . '/lphenom_kphp_none_' . uniqid() . '.php';

        try {
            $generator = KphpEntrypointGenerator::createDefault($this->basePath);
            $generator->generate($outputPath);

            $content = file_get_contents($outputPath);
            self::assertIsString($content);

            // none files (Cli TUI tools) must NOT appear
            self::assertStringNotContainsString('Cli/Screen/', $content);
            self::assertStringNotContainsString('Cli/Terminal/', $content);
            self::assertStringNotContainsString('Cli/Widget/', $content);
            self::assertStringNotContainsString('Cli/Config/', $content);
            self::assertStringNotContainsString('Cli/Adapter/', $content);
        } finally {
            if (is_file($outputPath)) {
                unlink($outputPath);
            }
        }
    }

    public function testIncludesKphpCompatibleFiles(): void
    {
        $outputPath = sys_get_temp_dir() . '/lphenom_kphp_incl_' . uniqid() . '.php';

        try {
            $generator = KphpEntrypointGenerator::createDefault($this->basePath);
            $generator->generate($outputPath);

            $content = file_get_contents($outputPath);
            self::assertIsString($content);

            // Core classes (no annotation = builds everywhere)
            self::assertStringContainsString('Config/Config.php', $content);
            self::assertStringContainsString('Container/Container.php', $content);
            self::assertStringContainsString('Application.php', $content);

            // shared,kphp classes
            self::assertStringContainsString('RespClient.php', $content);
            self::assertStringContainsString('RespRedisClient.php', $content);
            self::assertStringContainsString('FfiMySqlConnection.php', $content);
        } finally {
            if (is_file($outputPath)) {
                unlink($outputPath);
            }
        }
    }

    public function testGeneratedFileDoesNotExistInRepo(): void
    {
        $generatedPath = $this->basePath . '/build/kphp-entrypoint.generated.php';

        // The generated file should NOT exist before build:kphp runs
        // (it's gitignored and not committed)
        // If it exists from a previous test run, that's OK — but
        // we verify it's listed in .gitignore
        $gitignore = file_get_contents($this->basePath . '/.gitignore');
        self::assertIsString($gitignore);
        self::assertStringContainsString('kphp-entrypoint.generated.php', $gitignore);
    }

    public function testOldManualEntrypointNotPresent(): void
    {
        // The old build/kphp-entrypoint.php (manually maintained) should not exist
        $oldPath = $this->basePath . '/build/kphp-entrypoint.php';
        self::assertFileDoesNotExist($oldPath, 'Old manual kphp-entrypoint.php should be removed — it is now auto-generated');
    }

    public function testExcludesDevPackageFiles(): void
    {
        $generator = KphpEntrypointGenerator::createDefault($this->basePath);
        $files = $generator->getKphpFiles();

        $fileNames = array_map('basename', $files);

        // No dev package files should be included
        self::assertNotContains('TestCase.php', $fileNames);
        self::assertNotContains('phpunit', $fileNames);

        // All files should be from src/ or vendor/lphenom/
        foreach ($files as $file) {
            $inSrc = strpos($file, $this->basePath . '/src/') === 0;
            $inLphenomVendor = strpos($file, $this->basePath . '/vendor/lphenom/') === 0;
            self::assertTrue(
                $inSrc || $inLphenomVendor,
                "Unexpected file in kphp build: {$file}"
            );
        }
    }
}

